name: Working_Days_Calculator
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: damien <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  intl: ^0.15.7

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.30
